### ISSUE TITLE
Ability to load icons from wowhead

### ISSUE THREAD

**Issue by ljosberinn** [TobiasM95/WoW-Talent-Tree-Manager#12]
hey!

I've set myself on creating a tree for demon hunters, only to find that none of the existing images would be viable since they appear to be scraped from existing talent trees on wowhead.

would it be possible to allow using icons from the `resources/icons/{number}/img.png` folder directly or even easier, allowing importing from [wowhead directly](https://www.wowhead.com/icons)? creating a tree with mostly placeholder icons would alternatively work aswell but is naturally hard to use since you'd have unfamiliar / default ? icons for the majority of abilities.

**Comment by TobiasM95** [comment]
hey,

shipped icons are the "official" talent tree icons that are currently given by Wowhead. This functions as the base icon set that everyone that uses TTM has out of the box without the need for custom icons.
When creating a custom tree or editing an existing one, you can access all those base icons in the tree editor as usual. In addition to that, TTM supports custom icons in a straightforward manner. The "Controls & Tips" section accessible from the menu bar has instructions on how to use your own icons. Sadly this description is a little bit deprecated and I forgot to update it when I made changes to the resource location in the last update.
 **To implement custom icons:**
Put .png icons of the size 40x40 pixels with simple filenames (only letters and numbers to be safe) in `%APPDATA%\Roaming\WoWTalentTreeManager\resources\icons\custom` (you will need to create the `custom` folder) and restart the application. This should make the icons available in TTM.

As for importing from Wowhead, I currently don't have any plans on implementing such a feature. Not sure how this will change going forward but the need for custom icons will decrease once all trees are released.
I'll leave this issue open until the next version releases and then I'll mark it as close if nothing else arises.

**Comment by ljosberinn** [comment]
oh I didnt know about the custom folder, gonna try that, thank you :)

**Comment by TobiasM95** [comment]
The "Controls & Tips" screen now has the correct instructions for custom icons. I'll mark this issue as closed.
