### ISSUE TITLE
Pre-filled talents not saving when child node

### ISSUE THREAD

**Issue by sshawnsamuell** [TobiasM95/WoW-Talent-Tree-Manager#14]
Child nodes set to pre-filled do not persist when saving/loading, only the parent talent is pre-filled on load/import.
The enhancement Shaman class tree, with Chain Lightning and Maelstrom Weapons under both being prefilled, would be an example of this working.

**Comment by TobiasM95** [comment]
Thanks for the report.
I'm currently unable to investigate but could you please clarify a bit what you mean specifically?
Is the enhancement shaman preset incorrect/missing pre filled talents? Are prefilled talents not saved when editing custom trees?
Also, being prefilled shouldn't depend on parent/child nodes, can you also provide some steps to reproduce this issue?

**Comment by sshawnsamuell** [comment]
Okay, this can possibly be closed.
I wasn't able to recreate this when making new custom trees.
I think it was because I was using a preset tree and modified that instead of creating a new custom tree. I tried deleting the nodes and recreating them and now it saves the prefill option correctly.

**Comment by TobiasM95** [comment]
Alright, I'll close the issue for now as long as it's not happening again.
