### ISSUE TITLE
Add the ability to configure point gating

### ISSUE THREAD

**Issue by seanpeters86** [TobiasM95/WoW-Talent-Tree-Manager#29]
Right now you can select a set of points and say you must put at least 1 point in the group. It would be great if that "1" could be configured so that I could say "at least pick 2 points in this group".

**Comment by TobiasM95** [comment]
That'd be an interesting feature which I'm not sure if it's possible due to the optimized filtering code. However, since TTM is unofficially in maintenance mode for the time being, without any new features on my current todo list, this will not be integrated in the near future
